window.abb = {};
php = {};
window.PHP = {};
PHP.ajax = "wp-admin/admin-ajax.html";
PHP.wp_p_id = "5";
var indi_header_parallax, indi_banner_parallax, indi_page_parallax, indi_footer_parallax, indi_body_parallax;
var indi_images_dir = "wp-content/themes/Indicode/indicode/assets/images/index.html",
indi_theme_js_path = "wp-content/themes/Indicode/indicode/assets/js/index.html",
        indi_theme_dir = "wp-content/themes/Indicode/indicode/index.html",
        indi_captcha_placeholder = "Enter Captcha",
        indi_captcha_invalid_txt = "Invalid. Try again.",
        indi_captcha_correct_txt = "Captcha correct.",
        indi_responsive_nav_width = 1140,
        indi_vertical_header_back = "Back",
        indi_vertical_header_anim = "1",
        indi_check_rtl = true,
        indi_grid_width = 1140,
        indi_ajax_search_option = "disable",
        indi_preloader_bg_color = "#ffffff",
        indi_accent_color = "#fac42b",
        indi_go_to_top =  "true",
        indi_smooth_scroll =  "true",
        indi_preloader_bar_color = "#fac42b",
        indi_preloader_logo = "";
        var indi_header_parallax = false,
        indi_banner_parallax = false,
        indi_footer_parallax = false,
        indi_body_parallax = false,
        indi_no_more_posts = "No More Posts",
        indi_typekit_id   = "",
        indi_google_fonts = ["Open Sans:100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic,100,200,300,400,500,600,700,800,900"],
        indi_global_lazyload = true;
